# Site settings
author: Matthew DeBlock
title: Pure Brew Analytics
header-img: img/home-bg.png
email: matt_deblock@yahoo.com
copyright_name: Matthew DeBlock
description: > # this means to ignore newlines until "baseurl:"
  Pure Brew Analytics
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mattdeblock-lv

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
